version: '3.7'

services:
  database:
    image: postgres
    container_name: database_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rentalx
      - POSTGRES_PASSWORD=rentalx
      - POSTGRES_DB=rentalx_db_postgres
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentalx-api
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
